{% set name = "ghp-import" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 947b3771f11be850c852c64b561c600fdddf794bab363060854c1ee7ad05e071

build:
  number: 0
  noarch: python
  entry_points:
    - ghp-import = ghp_import:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.8.1

test:
  imports:
    - ghp_import
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/davisp/ghp-import
  license: LicenseRef-Tumbolia-Public
  license_file: LICENSE
  summary: Copy your docs directly to the gh-pages branch.

extra:
  recipe-maintainers:
    - ocefpaf
