{% set name = "ghp-import" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df19577f8e6fa3e96a84c5bb95a5040fe2d87c29cb6e99caae12ceb01896c5e7

build:
  noarch: python
  number: 0
  entry_points:
    - ghp-import = ghp_import:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - ghp-import --help

about:
  home: http://github.com/davisp/ghp-import
  license: Tumbolia Public
  license_file: LICENSE
  summary: Copy your docs directly to the gh-pages branch.

extra:
  recipe-maintainers:
    - ocefpaf
