{% set version = "0.5.5" %}

package:
  name: ghp-import
  version: {{ version }}

source:
  fn: ghp-import-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/ghp-import/ghp-import-{{ version }}.tar.gz
  sha256: 3e924ea720e4e1f82d56753db2154bfb86067472c5830732159c3a4c4fbc75d7

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - ghp-import --help

about:
  home: http://github.com/davisp/ghp-import
  license: Tumbolia Public
  license_file: LICENSE
  summary: 'Copy your docs directly to the gh-pages branch.'

extra:
  recipe-maintainers:
    - ocefpaf
