{% set version = "0.5.4" %}

package:
  name: ghp-import
  version: {{ version }}

source:
  fn: ghp-import-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/ghp-import/ghp-import-{{ version }}.tar.gz
  sha256: 65d576f107e2a52abdd10866476053a8c2c8ad7e2148a62bc0bc23f501b924cc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - ghp-import --help

about:
  home: http://github.com/davisp/ghp-import
  license: Tumbolia Public License
  license_file: LICENSE
  summary: 'Copy your docs directly to the gh-pages branch.'

extra:
  recipe-maintainers:
    - ocefpaf
