# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jj7XVPDp7+3VvVcnRhWu+lXKHBo2CuPmsG/4W+oTrMFpr6JWCaaIq9fvQRYG/BvfUmkpIgdC56dAAkhRMa30rL/6E1f+PnJS5ivhB13yJfJ0zSGJh8/EDF5b01ye3dAEAK/I8Xb9lJXblGqqrmixuZq++sLIlRJDIXTJiXrLv7LaN1zb915Qo+dwYdav3AMVRDqlLxcGjjD5AkTSlSMqdgfHNYnMYrz9vxVbOmm3KL1plxfaFnF3tNmZAzTtb5lgcs4D4wBZp3biE0Gw2DPd+4K5dR27q9EwYKatURFJV+AMIv2QHm+hgy4pRAWi0l4jRMGVYDboBQ+ivbOuq4puw81TYfr8euC8VLOyz/70SiqRFfl+EasdKp6YQTgRLs1u2sD533naHRAPP/23fgHtaSOeWyLbz19bjPFZMyTEF6Uug+ZRLMXF/a6lcxhbuy/Ntv9WeBizJCiUDURK9xzhlmsIPVUEhP9BVZ+9WKpa4ULzvbCTlcJCClgxcc2FH+A0Rrdvb6t7BKb5E7fpdsoxFPa53u8JBC2LN9LCNzznSNVZ0dfINm4eYsabuUHwDalk8ZQWDRQ/xEWG6TRKo5hhanPljvUP6nBt5sNPF0qBql1UWj2U0ApBjWgFCib/5tY5FZC2rNSwE+YVYvW3ro1cePRkEdmymdo/hkSfHg531No="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
