travis:
  secure:
    BINSTAR_TOKEN: iu+RGx/QOmuCMcjBPRqx6RIP5YBG+tkpb9wqFH/zVUzdVeLPzP2TNOKkdrvqVpidQQxuAIWx9dknxT7f6GzjU3FmdbIcB1M6Akf+K+CjqmuuUTrPFTCJzIj1ou0kjbBXB648xQ/Iw8Qh3L44rcB1/98D8W76aJFNPEaMBLCulAKXTTE4xGFt2K3BTxphlmx9d7K7S6LyGnBCbEgz/7/85w2A/qKpU0fTXjR64EbuksgtufhfwSlWvE7pUzHRrpjTOc8q2zX1qEFL0kXQ60zBVAc7RtJUSkF7mhczdZ/ybbJOtPLa75y7Ig+uTYEUqJtuE0AtiyGtCj4m505uXJffuIxQ1oCPBC/n0aX6bLRjRKQIAiqEp8NDUL9SRuqdP4EiU8FgV4ELXZ3G2mpd01iAyNgCBJMi1zybDzvkNCzkDTXdf3jb7x2vGVr53x7NjL5W1riTtrCT/ih2KcXQW11w5O7YAEKWVgeMiiR2DfwXzN9+8rsmV/UeXSvRcy1Hpl+ZxefBouq7Rg/oFG+3rR5I3jR+mD8EN9kF56ZVp0pYi3ChTHFmhO6YCTLjPFsxsdv4rRzLNSMD8NYlXih0O2b5FjbL2TxlmxBW6sXAOvHV5UgVhlqXW9wXB5EwBktpIhNyQVB98SEhKwtlIMDJQjjaTzLbjrCAzQEhXyjK2ppmvy8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
