travis:
  secure:
    BINSTAR_TOKEN: e9G57JNt3QE4xK7J08PGxkLaqJBWWeVa92pJL19Y3OPWBFSLsN1QhYT0qS2RlF1QV/Mx6XTDb6TUaSAMNZ3bDoNnQef2R7jlx8IQ7cEVTB/d1jYrS5zyTgeXxwsPl9MnftDQkPXT2ejJZIC5k6EvRrRRZ5sp2kFr1P6QOcKz9Euite8U6TGVw65ms2pDvkmXZEzA4hYy1G0VWkC2X+0bqxaC1vVDHg0gl//IBODeCKRZibSfZihjFekCubVJAHDm9eQ2dIDrm/HlHPrl6LQB0Z8kTcnzHNaGaKLuXwWs0K0YN0718URpqZBVNzMqdJgaoxw0uJCHCgphATU4FGkE0vU5UgpH48vsL5zbE5lscW1IPPmQXHktnMjaIp9woeNX46pHYQ2YRao3o2PjjgJ0QC7FMe0jNZBBvSosRBvOToGl0fIO1xbZaPWfxM/Mey5RQsTrRt9Z/UJH878cBPsjPLP6M+FYUXMDVjUS8Gj1od+XkXL90YUB8KY4f1Dgdarh3HbTEB3IuM18Fa5DVw34nm6UNliezdZcWS8eXWWe2oR/KAA66dPt4IRO4L6vTJK3rwx8RsHwjeDJddeWz4BDnvYXTWyBNv3MXlAoSkOZ6jE3Cw/+8g5xSontjcK+iCA4B7XDDAu6spnt4Zq6DQCpqlsx7wHIVQlL8nBK8efIj/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
