travis:
  secure:
    BINSTAR_TOKEN: jj7XVPDp7+3VvVcnRhWu+lXKHBo2CuPmsG/4W+oTrMFpr6JWCaaIq9fvQRYG/BvfUmkpIgdC56dAAkhRMa30rL/6E1f+PnJS5ivhB13yJfJ0zSGJh8/EDF5b01ye3dAEAK/I8Xb9lJXblGqqrmixuZq++sLIlRJDIXTJiXrLv7LaN1zb915Qo+dwYdav3AMVRDqlLxcGjjD5AkTSlSMqdgfHNYnMYrz9vxVbOmm3KL1plxfaFnF3tNmZAzTtb5lgcs4D4wBZp3biE0Gw2DPd+4K5dR27q9EwYKatURFJV+AMIv2QHm+hgy4pRAWi0l4jRMGVYDboBQ+ivbOuq4puw81TYfr8euC8VLOyz/70SiqRFfl+EasdKp6YQTgRLs1u2sD533naHRAPP/23fgHtaSOeWyLbz19bjPFZMyTEF6Uug+ZRLMXF/a6lcxhbuy/Ntv9WeBizJCiUDURK9xzhlmsIPVUEhP9BVZ+9WKpa4ULzvbCTlcJCClgxcc2FH+A0Rrdvb6t7BKb5E7fpdsoxFPa53u8JBC2LN9LCNzznSNVZ0dfINm4eYsabuUHwDalk8ZQWDRQ/xEWG6TRKo5hhanPljvUP6nBt5sNPF0qBql1UWj2U0ApBjWgFCib/5tY5FZC2rNSwE+YVYvW3ro1cePRkEdmymdo/hkSfHg531No=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
